# reveal-slides/Dockerfile.vega
FROM node:20-slim

RUN apt-get update && \
    apt-get install -y \
      libcairo2-dev \
      libpango1.0-dev \
      libjpeg-dev \
      libgif-dev \
      librsvg2-dev \
      build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g canvas vega-cli vega-lite

WORKDIR /work
CMD ["bash"]
