version: '3.8'

services:
  # データ取得ジョブ（短命・定期実行）
  gtfs-ingest:
    build:
      context: .
      dockerfile: docker/Dockerfile.ingest
      args:
        BASE_IMAGE: tram-base:latest
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./configs/google_drive:/app/configs/google_drive
    environment:
      - PYTHONPATH=/app/src
      - GOOGLE_DRIVE_ENABLED=true
    # 連続実行（20秒間隔でデータ取得）
    command: ["--feed-type", "all", "--interval", "20"]
    restart: unless-stopped

  # シミュレーション実行
  simulation:
    build:
      context: .
      dockerfile: docker/Dockerfile.sim
      args:
        BASE_IMAGE: tram-base:latest
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
      - SUMO_HOME=/opt/sumo
    command: ["--config", "configs/sim/toyama_tram.yaml"]
    restart: "no"

  # 学習実行
  training:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
      args:
        BASE_IMAGE: tram-base:latest
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
    command: ["--config", "configs/train/qddqn.yaml", "--episodes", "1000"]
    restart: "no"
    # GPU対応時は以下をコメントアウト
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

# ボリューム定義
volumes:
  data:
  models:
  results:
  logs:
