# NOTE: Do not use chmod 777 or 666.
# Use proper ownership (chown) and safe permissions instead (chmod 755).

# Common environment variables
x-common-environment: &common-environment
  PYTHONPATH: /app/src

services:
  # GTFS Static data ingestion (short-lived task)
  gtfs-ingest-static:
    image: tram-ingest:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.ingest
      args:
        BASE_IMAGE: tram-base:latest
        APP_UID: 1000
        APP_GID: 1000
    volumes:
      - ../data:/app/data:z
      - ../logs:/app/logs:z
      - ../configs:/app/configs:z
      - ../src:/app/src:z
      - ../scripts:/app/scripts:z
    environment: *common-environment
    # Single execution per container instance (Static data only)
    command: ["--feed-type", "gtfs_static", "--once"]
    restart: "no"  # Short-lived task
    profiles:
      - manual  # Run manually or via scheduler

  # GTFS-RT real-time data ingestion (short-lived task)
  gtfs-ingest-realtime:
    image: tram-ingest-realtime:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.ingest-realtime
      args:
        BASE_IMAGE: tram-base:latest
        APP_UID: 1000
        APP_GID: 1000
    volumes:
      - ../data:/app/data:z
      - ../logs:/app/logs:z
      - ../configs:/app/configs:z
    environment: *common-environment
    # Single execution per container instance (RT data only)
    command: ["--feed-type", "realtime", "--once"]
    restart: "no"  # Short-lived task
    profiles:
      - manual  # Run manually or via scheduler

  # Simulation execution
  simulation:
    image: tram-sim:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.sim
      args:
        BASE_IMAGE: tram-base:latest
    volumes:
      - ../data:/app/data:z
      - ../results:/app/results:z
      - ../logs:/app/logs:z
    environment:
      - PYTHONPATH=/app/src
      - SUMO_HOME=/opt/sumo
    command: ["--config", "configs/sim/toyama_tram.yaml"]
    restart: "no"

  # Training execution
  training:
    image: tram-train:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.train
      args:
        BASE_IMAGE: tram-base:latest
    volumes:
      - ../data:/app/data:z
      - ../models:/app/models:z
      - ../results:/app/results:z
      - ../logs:/app/logs:z
    environment:
      - PYTHONPATH=/app/src
    command: ["--config", "configs/train/qddqn.yaml", "--episodes", "1000"]
    restart: "no"
    # Uncomment the following for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

# Volume definitions
volumes:
  data:
  models:
  results:
  logs:
