version: '3.8'

services:
  # Data ingestion job (short-lived, periodic execution)
  gtfs-ingest:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ingest
      args:
        BASE_IMAGE: tram-base:latest
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
      - ../configs/google_drive:/app/configs/google_drive
    environment:
      - PYTHONPATH=/app/src
      - GOOGLE_DRIVE_ENABLED=true
      - BACKUP_INTERVAL=300  # Backup every 5 minutes
    # Continuous execution (data collection every 20 seconds) + Google Drive auto backup
    # command: ["--feed-type", "all", "--interval", "20"]  # Use default command
    restart: unless-stopped

  # Simulation execution
  simulation:
    build:
      context: ..
      dockerfile: docker/Dockerfile.sim
      args:
        BASE_IMAGE: tram-base:latest
    volumes:
      - ../data:/app/data
      - ../results:/app/results
      - ../logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
      - SUMO_HOME=/opt/sumo
    command: ["--config", "configs/sim/toyama_tram.yaml"]
    restart: "no"

  # Training execution
  training:
    build:
      context: ..
      dockerfile: docker/Dockerfile.train
      args:
        BASE_IMAGE: tram-base:latest
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../results:/app/results
      - ../logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
    command: ["--config", "configs/train/qddqn.yaml", "--episodes", "1000"]
    restart: "no"
    # Uncomment the following for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

# Volume definitions
volumes:
  data:
  models:
  results:
  logs:
