version: '3.8'

# NOTE: Do not use chmod 777 or 666.
# Use proper ownership (chown) and safe permissions instead (chmod 755).

# Common environment variables
x-common-environment: &common-environment
  PYTHONPATH: /app/src
  RCLONE_ENABLED: "false"
  GOOGLE_DRIVE_ENABLED: "false"

# Common volumes
x-common-volumes: &common-volumes
  - ../data:/app/data
  - ../logs:/app/logs
  - ../configs:/app/configs

# Rclone config volume
x-rclone-volume: &rclone-volume
  - ~/.config/rclone:/home/appuser/.config/rclone:ro

services:
  # GTFS Static data ingestion (short-lived task)
  gtfs-ingest-static:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ingest
      args:
        BASE_IMAGE: tram-base:latest
        APP_UID: 1000
        APP_GID: 1000
    volumes: *common-volumes
    environment: *common-environment
    # Single execution per container instance (Static data only)
    command: ["--feed-type", "gtfs_static", "--once"]
    restart: "no"  # Short-lived task
    profiles:
      - manual  # Run manually or via scheduler

  # GTFS-RT real-time data ingestion (short-lived task)
  gtfs-ingest-realtime:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ingest-realtime
      args:
        BASE_IMAGE: tram-base:latest
        APP_UID: 1000
        APP_GID: 1000
    volumes:
      - ../data/raw:/app/data        
      - ../logs:/app/logs
      - ../configs:/app/configs
    environment: *common-environment
    # Single execution per container instance (RT data only)
    command: ["--feed-type", "all", "--once"]
    restart: "no"  # Short-lived task
    profiles:
      - manual  # Run manually or via scheduler

  # # Backup job (short-lived task)
  # backup:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile.backup
  #     args:
  #       BASE_IMAGE: tram-base:latest
  #       APP_UID: 1000
  #       APP_GID: 1000
  #   volumes:
  #     - ../data:/app/data
  #     - ../logs:/app/logs
  #     - ../configs:/app/configs
  #     - ~/.config/rclone:/home/appuser/.config/rclone:ro
  #   environment:
  #     <<: *common-environment
  #     BACKUP_INTERVAL: "60"  # Backup every 1 minute for real-time data
  #   # Single execution per container instance
  #   command: ["--once"]
  #   restart: "no"  # Short-lived task
  #   profiles:
  #     - manual  # Run manually or via scheduler

  # Simulation execution
  simulation:
    build:
      context: ..
      dockerfile: docker/Dockerfile.sim
      args:
        BASE_IMAGE: tram-base:latest
    volumes:
      - ../data:/app/data
      - ../results:/app/results
      - ../logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
      - SUMO_HOME=/opt/sumo
    command: ["--config", "configs/sim/toyama_tram.yaml"]
    restart: "no"

  # Training execution
  training:
    build:
      context: ..
      dockerfile: docker/Dockerfile.train
      args:
        BASE_IMAGE: tram-base:latest
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../results:/app/results
      - ../logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
    command: ["--config", "configs/train/qddqn.yaml", "--episodes", "1000"]
    restart: "no"
    # Uncomment the following for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

# Volume definitions
volumes:
  data:
  models:
  results:
  logs:
