name: Test CDDDQN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test with pytest
      run: |
        python -c "import torch; import matplotlib; import numpy; print('All imports successful')"
    
    - name: Run CDDDQN (quick test)
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from cdddqn_min import GridWorld, CDDDQN
        print('CDDDQN classes imported successfully')
        "
